# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'InstargramApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SVProgressHUD'

  # Pods for InstargramApp

  target 'InstargramAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstargramAppUITests' do
    # Pods for testing
  end

end
